nascosto output ypinit e controllo esito

diff --git a/labsis-cambio-password b/labsis-cambio-password
--- a/labsis-cambio-password
+++ b/labsis-cambio-password
@@ -7,18 +7,30 @@ versione="1.0.0"
 
 # USO:
 # TODO: scrivere l'uso
-echo "cambio password per  $USER "
+#echo "cambio password per  $USER "
 passwd  $USER
 exitcodepasswd=$?
-echo $exitcodepasswd 
 
 if [ $exitcodepasswd -ne 0 ]
 then
-  echo "qualcosa è andato storto nel cambio password"
-  echo " il cambio ha prodotto l'exit code $exitcode-passwd"
+  echo "qualcosa è andato storto !!!"
+  echo " cambio password non riuscito "
+  echo " exit code = 1 "
   exit 1
 else
-  (echo -e "\n" ) | sudo /usr/lib/yp/ypinit -m
-  exit 0
+  (echo -e "\n" ) | sudo /usr/lib/yp/ypinit -m  &> /dev/null 
+  exitcodepasswd=$?
+  if [ $exitcodepasswd -ne 0 ]
+  then
+       echo "qualcosa è andato storto !!!"
+       echo " cambio password non riuscito "
+       echo "POTRESTI NON POTER ACCEDERE ALSISTEMA "
+       echo "segnalare questo errore agli amministratori "
+       echo " exit code = 2 "
+       exit 2
+  else 
+     exit 0
+  fi
+
 fi
 
